name: a_to_z_ui
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^7.1.1
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  provider: ^6.1.2
  a_to_z_widgets:
    path: ../a_to_z_widgets
  audioplayers: ^6.5.1
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.2.3
  my_widgets:
    path: ../my_widgets
  a_to_z_providers:
    path: ../a_to_z_providers
  a_to_z_dto:
    path: ../a_to_z_dto
  a_to_z_api_connect:
    path: ../a_to_z_api_connect
  http: ^1.5.0
  audio_session: ^0.2.2
  animated_text_kit: ^4.2.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ATOZ_ICON.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/ATOZ_ICON.jpg
    - assets/app_icon2.png
    - assets/dubai_song.mp3